/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppContainer {
    'identifier': number;
    'name': string;
  }
  interface AppHome {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppContainerElement extends Components.AppContainer, HTMLStencilElement {}
  var HTMLAppContainerElement: {
    prototype: HTMLAppContainerElement;
    new (): HTMLAppContainerElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-container': HTMLAppContainerElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppContainer {
    'identifier': number;
    'name'?: string;
    'onBack'?: (event: CustomEvent<any>) => void;
    'onNext'?: (event: CustomEvent<any>) => void;
  }
  interface AppHome {}
  interface AppRoot {}

  interface IntrinsicElements {
    'app-container': AppContainer;
    'app-home': AppHome;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-container': LocalJSX.AppContainer & JSXBase.HTMLAttributes<HTMLAppContainerElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


